[SPC-level-list]
text = '''
Table that displays a list of all levels.

Shows:
* Name - (num + sublevel letter)
* Solved By
* Status - Completed / In Progress / Locked 
'''

[TST-level-list]
text = '''
Provision fake levels and fake user completions/attempts of those levels.

Assert that a certain number of levels are displayed and the tables fields are correct for the test user.
'''